logos-polytechnikos.cz/src/Entity/User.php
<?php declare(strict_types = 1);

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Serializable;
use Symfony\Component\Security\Core\User\UserInterface;
use function serialize;
use function trim;
use function unserialize;

/**
 * @ORM\Entity()
 */
class User implements UserInterface, Serializable
{

	/**
	 * @ORM\Id()
	 * @ORM\GeneratedValue()
	 * @ORM\Column(type="integer")
	 * @var int|null
	 */
	private $id;

	/**
	 * @ORM\Column(type="string", length=20, unique=true, name="login")
	 * @var string|null
	 */
	private $username;

	/**
	 * @ORM\Column(type="string", length=100)
	 * @var string|null
	 */
	private $password;

	/**
	 * @ORM\Column(type="string", length=40, nullable=true)
	 * @var string
	 */
	private $titleBeforeName;

	/**
	 * @ORM\Column(type="string", length=40, nullable=true)
	 * @var string
	 */
	private $titleAfterName;

	/**
	 * @ORM\Column(type="string", length=100)
	 * @var string|null
	 */
	private $name;

	/**
	 * @ORM\Column(type="string", length=100)
	 * @var string
	 */
	private $surname;

	/**
	 * @ORM\Column(type="string", length=100, unique=true)
	 * @var string|null
	 */
	private $email;

	/**
	 * @ORM\ManyToOne(targetEntity="App\Entity\UserRole", inversedBy="usersRole")
	 * @var UserRole|null
	 */
	private $role;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="reviewer")
	 * @var Collection|Review[]|null
	 */
	private $reviews;

	/**
	 * @ORM\Column(type="datetime_immutable", nullable=true)
	 * @var DateTimeImmutable|null
	 */
	private $insertDate;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="author")
	 * @var Collection|Article[]|null
	 */
	private $articles;

	/**
	 * @ORM\Column(type="datetime_immutable")
	 * @ORM\JoinColumn(nullable=true)
	 * @var DateTimeImmutable|null
	 */
	private $lastReadComment;

	/** @var string|null */
	private $rolePlainText;

	public function __construct()
	{
		$this->reviews = new ArrayCollection();
		$this->articles = new ArrayCollection();
		$this->insertDate = new DateTimeImmutable();
	}

	public function getFullName(): string
	{
		$fullName = '';
		if ($this->titleBeforeName !== null && trim($this->titleBeforeName) !== '') {
			$fullName .= $this->titleBeforeName . ' ';
		}
		$fullName .= $this->getFullNameByName();
		if ($this->titleAfterName !== null && trim($this->titleAfterName) !== '') {
			$fullName .= ', ' . $this->titleAfterName;
		}
		return $fullName;
	}

	public function getFullNameByName(): ?string
	{
		return $this->name . ' ' . $this->surname;
	}

	public function getFullNameBySurname(): ?string
	{
		return $this->surname . ' ' . $this->name;
	}

	/**
	 * @return string[]
	 */
	public function getRoles(): array
	{
		return [
			$this->role->getRole(),
		];
	}

	public function getSalt(): void
	{
		/** nutná implementace z interface */
	}

	public function eraseCredentials(): void
	{
		/** nutná implementace z interface */
	}

	public function serialize()
	{
		return serialize([
			$this->id,
			$this->username,
			$this->email,
			$this->password,
			$this->titleBeforeName,
			$this->titleAfterName,
			$this->name,
			$this->surname,
		]);
	}

	public function unserialize($serialized): void
	{
		[
			$this->id,
			$this->username,
			$this->email,
			$this->password,
			$this->titleBeforeName,
			$this->titleAfterName,
			$this->name,
			$this->surname,
		] = unserialize($serialized, ['allowed_classes' => false]);
	}

	public function getId(): ?int
	{
		return $this->id;
	}

	public function setId(?int $id): void
	{
		$this->id = $id;
	}

	public function getUsername(): ?string
	{
		return $this->username;
	}

	public function setUsername(?string $username): void
	{
		$this->username = $username;
	}

	public function getPassword(): ?string
	{
		return $this->password;
	}

	public function setPassword(?string $password): void
	{
		$this->password = $password;
	}

	public function getTitleBeforeName(): ?string
	{
		return $this->titleBeforeName;
	}

	public function setTitleBeforeName(?string $titleBeforeName): void
	{
		$this->titleBeforeName = $titleBeforeName;
	}

	public function getTitleAfterName(): ?string
	{
		return $this->titleAfterName;
	}

	public function setTitleAfterName(?string $titleAfterName): void
	{
		$this->titleAfterName = $titleAfterName;
	}

	public function getName(): ?string
	{
		return $this->name;
	}

	public function setName(?string $name): void
	{
		$this->name = $name;
	}

	public function getSurname(): ?string
	{
		return $this->surname;
	}

	public function setSurname(string $surname): void
	{
		$this->surname = $surname;
	}

	public function getEmail(): ?string
	{
		return $this->email;
	}

	public function setEmail(?string $email): void
	{
		$this->email = $email;
	}

	public function getRole(): ?UserRole
	{
		return $this->role;
	}

	public function setRole(?UserRole $role): void
	{
		$this->role = $role;
	}

	public function getRolePlainText(): ?string
	{
		return $this->rolePlainText;
	}

	public function setRolePlainText(?string $rolePlainText): void
	{
		$this->rolePlainText = $rolePlainText;
	}

	/**
	 * @return Review[]|Collection|null
	 */
	public function getReviews()
	{
		return $this->reviews;
	}

	/**
	 * @param Review[]|Collection|null $reviews
	 */
	public function setReviews($reviews): void
	{
		$this->reviews = $reviews;
	}

	public function getInsertDate(): ?DateTimeImmutable
	{
		return $this->insertDate;
	}

	public function setInsertDate(?DateTimeImmutable $insertDate): void
	{
		$this->insertDate = $insertDate;
	}

	/**
	 * @return Article[]|Collection|null
	 */
	public function getArticles()
	{
		return $this->articles;
	}

	/**
	 * @param Article[]|Collection|null $articles
	 */
	public function setArticles($articles): void
	{
		$this->articles = $articles;
	}

	public function getLastReadComment(): ?DateTimeImmutable
	{
		return $this->lastReadComment;
	}

	public function setLastReadComment(?DateTimeImmutable $lastReadComment): void
	{
		$this->lastReadComment = $lastReadComment;
	}

}

logos-polytechnikos.cz/templates/rsp/about.html.twig
<div class="row justify-content-center">
    <div class="col col-xl-10 col-lg-12">
        <div class="row">
            <div class="col-xl-9">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">O časopise LOGOS POLYTECHNIKOS
                    {% if is_granted('ROLE_REDAKTOR') %}
                        <a class="btn btn-sm btn-outline-secondary"
                           title="Upravit pokyny pro přispěvatele"
                           href="{{ path('app_index_changeabout') }}"><i class="fa fa-pen"></i>
                        </a>
                    {% endif %}
                    </div>
                    <div class="card-body">
                        {% if setting.settings.about is not null %}
                            {{ setting.settings.about|replace({'%sablona%': '<a href="' ~ path('app_file_downloadtemplate', {template: setting.settings.activeTemplate.id}) ~ '">Šablona</a>'})|raw }}
                        {% else %}
                            <div class="alert alert-warning">Informace o časopise LOGOS POLYTECHNIKOS nebyly vyplněny.</div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-xl-3">
                <div class="card" style="position: sticky; top: 40px;">
                    <div class="card-header d-flex justify-content-between">Kontakt
                        {% if is_granted('ROLE_REDAKTOR') %}
                            <a class="btn btn-sm btn-outline-secondary"
                               title="Upravit pokyny pro přispěvatele"
                               href="{{ path('app_index_changecontact') }}"><i class="fa fa-pen"></i>
                            </a>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        {% if setting.settings.contact is not null %}
                            {{ setting.settings.contact|raw }}
                        {% else %}
                            <div class="alert alert-warning">Kontakt na časopis LOGOS POLYTECHNIKOS nebyl vyplněn.</div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

logos-polytechnikos.cz/templates/rsp/change_about.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col col-xl-8 col-lg-12">
            <div class="card">
                {{ form_start(form) }}
                    <div class="card-header">Upravujete informace o časopise na úvodní stránce</div>
                    <div class="card-body">
                        {{ form_widget(form.about) }}
                    </div>
                    <div class="card-footer">
                        {{ form_rest(form) }}
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
        {{ include('info_variables.html.twig') }}
    </div>
{% endblock %}

logos-polytechnikos.cz/templates/rsp/change_contact.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col col-xl-10 col-lg-12">
            <div class="card">
                {{ form_start(form) }}
                    <div class="card-header">Upravujete kontaktní informace na úvodní stránce</div>
                    <div class="card-body">
                        {{ form_widget(form.contact) }}
                    </div>
                    <div class="card-footer">
                        {{ form_rest(form) }}
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

logos-polytechnikos.cz/templates/rsp/change_instructions.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col col-xl-8 col-lg-12">
            <div class="card">
                {{ form_start(form) }}
                    <div class="card-header">Upravujete pokyny pro přispěvatele</div>
                    <div class="card-body">
                        {{ form_widget(form.instructions) }}
                    </div>
                    <div class="card-footer">
                        {{ form_rest(form) }}
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
        {{ include('info_variables.html.twig') }}
    </div>
{% endblock %}

logos-polytechnikos.cz/templates/rsp/change_review_management.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col col-xl-10 col-lg-12">
            <div class="card">
                {{ form_start(form) }}
                    <div class="card-header">Upravujete recenzní řízení</div>
                    <div class="card-body">
                        {{ form_widget(form.reviewManagement) }}
                    </div>
                    <div class="card-footer">
                        {{ form_rest(form) }}
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

logos-polytechnikos.cz/templates/rsp/change_template.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    {% if is_granted('ROLE_REDAKTOR') %}
    <div class="row justify-content-center">
        <div class="col col-xl-5 col-lg-6">
            <div class="card">
                {{ form_start(form) }}
                    <div class="card-header">Upravujete šablonu příspěvku</div>
                    <div class="card-body">
                        <div class="form-group">
                            {{ form_label(form.articleTemplate) }}
                            {{ form_widget(form.articleTemplate) }}
                            {{ form_help(form.articleTemplate) }}
                        </div>
                    </div>
                    <div class="card-footer">
                        {{ form_rest(form) }}
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
        <div class="col col-xl-5 col-lg-6">
            <div class="card">
                <div class="card-header">Aktuální šablona</div>
                <div class="card-body">
                    {% if setting.settings.activeTemplate is not null %}
                        <a title="Stáhnout šablonu"
                           href="{{ path('app_file_downloadtemplate', {template: setting.settings.activeTemplate.id}) }}">{{ setting.settings.activeTemplate.articleTemplate.fileName }}
                        </a>
                    {% else %}
                    Šablona zatím nebyla vložena.
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row justify-content-center" style="margin-top: 2rem;">
        <div class="col col-xl-10 col-lg-12">
            <div class="card">
                <div class="card-header">Přehled šablon</div>
                <div class="card-body">
                    {% if templates|length > 0 %}
                    <div class="list-group">
                        <div class="list-group-item list-group-item-info">
                            <div class="row">
                                <div class="col-md-4">Název</div>
                                <div class="col-md-3">Ze dne</div>
                                <div class="col-md-4">Vložil</div>
                                {% if is_granted('ROLE_REDAKTOR') %}
                                <div class="col-md-1">Akce</div>
                                {% endif %}
                            </div>
                        </div>
                    {% for template in templates%}
                        <div class="list-group-item {% if setting.settings.activeTemplate.id == template.id  %}list-group-item-success{% endif %}">
                            <div class="d-flex row">
                                <div class="col-md-4">
                                    <a title="Stáhnout šablonu"
                                       href="{{ path('app_file_downloadtemplate', {template: template.id}) }}">{{ template.articleTemplate.fileName }}</a>
                                </div>
                                <div class="col-md-3">{{ template.date|date('d.m.Y, H:i:s') }}</div>
                                <div class="col-md-4">{{ template.whoChanged.fullNameByName }}</div>
                                {% if is_granted('ROLE_REDAKTOR') %}
                                <div class="col-md-1">
                                    {% if setting.settings.activeTemplate.id != template.id  %}
                                    <a title="Nastavit jako aktuální šablonu."
                                       data-confirm-title="Změna výchozí šablony"
                                       data-confirm-text="Opravdu si přeje změnit šablonu na: {{ template.articleTemplate.fileName }}?"
                                       class="btn btn-sm btn-warning confirm"
                                       href="{{ path('app_index_setdefaulttemplate', {template: template.id}) }}"><i class="fa fa-cog"></i>
                                    </a>
                                    {% endif %}
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                    {% else %}
                    Žádna šablona zatím nebyla vložena.
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('changeTemplate') }}
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('changeTemplate') }}
{% endblock %}

logos-polytechnikos.cz/templates/rsp/index.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    {# todo: doddělat widgety úvodní stránka #}
    {% if app.user is null %}
        {% include "rsp/about.html.twig" %}
        {# include 'article/public_articles_widget.html.twig' #}
    {% endif %}
    {% if is_granted('ROLE_REDAKTOR') or is_granted('ROLE_SEFREDAKTOR') %}
        {% include 'article/redaktor_widget.html.twig' %}
    {% endif %}
    {% if is_granted('ROLE_RECENZENT') %}
        {% include 'article/recenzent_widget.html.twig'%}
    {% endif %}

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('rspIndex') }}
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('rspIndex') }}
{% endblock %}

logos-polytechnikos.cz/templates/rsp/show_about.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    {% include "/rsp/about.html.twig" %}
{% endblock %}

logos-polytechnikos.cz/templates/rsp/show_instructions.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col col-xl-10 col-lg-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between d-flex justify-content-between">Pokyny pro přispěvatele
                    {% if is_granted('ROLE_REDAKTOR') %}
                    <a class="btn btn-sm btn-warning"
                       title="Upravit pokyny pro přispěvatele"
                       href="{{ path('app_index_changeinstruction') }}"><i class="fa fa-pen"></i>
                    </a>
                    {% endif %}
                </div>
                    <div class="card-body">
                    {% if setting.settings.instructions is not null %}
                        {{ setting.settings.instructions|replace({'%sablona%': '<a href="' ~ path('app_file_downloadtemplate', {template: setting.settings.activeTemplate.id}) ~ '">Šablona</a>'})|raw }}
                    {% else %}
                        <div class="alert alert-warning">Instrukce zatím nebyly vyplněny.</div>
                    {% endif %}
                    </div>
            </div>
        </div>
    </div>
{% endblock %}

logos-polytechnikos.cz/templates/rsp/show_review_management.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col col-xl-10 col-lg-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">Recenzní řízení
                {% if is_granted('ROLE_REDAKTOR') %}
                    <a class="btn btn-sm btn-warning"
                       title="Upravit pokyny pro přispěvatele"
                       href="{{ path('app_index_changereviewmanagement') }}"><i class="fa fa-pen"></i>
                    </a>
                {% endif %}
                </div>
                <div class="card-body">
                    {% if setting.settings.reviewManagement is not null %}
                        {{ setting.settings.reviewManagement|raw }}
                    {% else %}
                        <div class="alert alert-warning">Popis recenzního řízení zatím nebyl vyplněn.</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}